[build]
builder = "nixpacks"

[deploy]
startCommand = "vendor/bin/heroku-php-apache2 public/"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "postgresql"
QUEUE_CONNECTION = "database"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
LOG_CHANNEL = "stack"
MAIL_MAILER = "smtp"
MAIL_HOST = "smtp.gmail.com"
MAIL_PORT = "587"
MAIL_ENCRYPTION = "tls"
MAIL_FROM_ADDRESS = "noreply@school.edu"
MAIL_FROM_NAME = "School Discipline Tracker"





