services:
  - type: web
    name: discipline-tracker
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://discipline-tracker.onrender.com
      - key: DB_CONNECTION
        value: postgresql
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: LOG_CHANNEL
        value: stack
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: noreply@school.edu
      - key: MAIL_FROM_NAME
        value: "School Discipline Tracker"
    healthCheckPath: /
    autoDeploy: true

  - type: worker
    name: discipline-tracker-worker
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: true
      - key: DB_CONNECTION
        value: postgresql
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: LOG_CHANNEL
        value: stack
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: noreply@school.edu
      - key: MAIL_FROM_NAME
        value: "School Discipline Tracker"

databases:
  - name: discipline-tracker-db
    databaseName: discipline_tracker
    user: discipline_tracker_user
